### ISSUE TITLE
运行报错：NameError: name 'path_name' is not defined

### ISSUE THREAD

**Issue by libhot** [kevin-meng/HuggingfaceDownloadShare#2]
通过FQ确认下载成功，但是上传到百度网盘时报错：
Fetching 4 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 55188.21it/s]
mv: invalid option -- 'r'
Try 'mv --help' for more information.
/usr/local/lib/python3.10/dist-packages/gradio/helpers.py:779: UserWarning: Unexpected argument. Filling with None.
  warnings.warn("Unexpected argument. Filling with None.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 508, in predict
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/opt/hf/app.py", line 21, in upload_by_path
    path_name
NameError: name 'path_name' is not defined

**Comment by kevin-meng** [comment]
已更新
